{
    "Parameters": {
        "StockBuffer": {
            "Molecule": "X-Glucuro",
            "TargetConc": "100mg/ml",
            "MoleculeDensity": "1000kg/m^3",
            "Diluent":"DMSO",
            "Vessel":"1L_DuranBottle",
            "TotalVolume": "10ml"
        }
    }
}
