{
    "Parameters": {
        "AccuracyTest": {
            "Diluent": "water",
            "TestSols": [
			"tartrazine"
			],
            "NumberofReplicates": 1,
            "OutPlate": "greiner384_riser",
            "TestSolVolumes": [
			"0.5ul",
			"1ul",
			"2ul"
			],
			"UseLiquidPolicyForTestSolutions": true,
			"LHPolicy":"NeedToMix",
			"DXORJMP":"JMP",
			"OutputFilename":"AccuracytestoeoutputSmall_test.xlsx",
			"Printasimage": true,
			"Imagefilename": "star.png",
            "TotalVolume": "20ul",
			"NumberofBlanks": 1
        }
    }
}

