{
    "Parameters": {
        "PCR": {
            "Projectname": "gradientPCRlividans",
			"RowGradientRatherthanColumn":false,
            "Reactiontoprimerpair": {
                "lefthomologyarm1kb": [
                    "LHA1kbF",
                    "LHAR4"
                ],
                "lefthomologyarm2.5kbA": [
                    "LHAF1",
                    "LHAR2"
                ],
                "lefthomologyarm2.5kbB": [
                    "LHAF3",
                    "LHAR4"
                ],
                "lefthomologyarm3kb": [
                    "LHA3kbF",
                    "LHAR4"
                ],
                "righthomologyarm1kb": [
                    "RHAF1",
                    "RHA1kbR"
                ],
                "righthomologyarm2.5kbA": [
                    "RHAF1",
                    "RHAR2"
                ],
                "righthomologyarm2.5kbB": [
                    "RHAF3",
                    "RHAR4"
                ],
                "righthomologyarm3kb": [
                    "RHAF1",
                    "RHA3kbR"
                ]
            },
            "Reactiontotemplate": {
                "lefthomologyarm1kb": "lividans",
                "lefthomologyarm2.5kbA": "lividans",
                "lefthomologyarm2.5kbB": "lividans",
                "lefthomologyarm3kb": "lividans",
                "righthomologyarm1kb": "pQR1059",
                "righthomologyarm2.5kbA": "lividans",
                "righthomologyarm2.5kbB": "pQR1059",
                "righthomologyarm3kb": "pQR1059"
            },
            "FwdPrimertype": "PrimerFw",
            "RevPrimertype": "PrimerRev",
            "Templatetype": "dna_part",
			"Plate": "pcrplate_skirted_riser"
        }
    }
}
