{
    "Parameters": {
        "RBS": {
            "OnlyreturnAvailableParts": true,
            "OnlyreturnWorkingparts": true,
			"ExactTypeOnly":false,
            "Partdescriptions": [
               "STRONG"
            ],
            "Parttype":
                "RBS"
            
        },
		"CyanReporter": {
            "OnlyreturnAvailableParts": true,
            "OnlyreturnWorkingparts": false,
			"ExactTypeOnly":true,
            "Partdescriptions": [
               "CYAN"
            ],
            "Parttype":
                "REPORTER"
            
        },
		"YellowReporter": {
            "OnlyreturnAvailableParts": true,
            "OnlyreturnWorkingparts": false,
			"ExactTypeOnly":true,
            "Partdescriptions": [
               "YELLOW"
            ],
            "Parttype":
                "REPORTER"
            
        },
		"GreenReporter": {
            "OnlyreturnAvailableParts": true,
            "OnlyreturnWorkingparts": false,
			"ExactTypeOnly":true,
            "Partdescriptions": [
               "GREEN"
            ],
            "Parttype":
                "REPORTER"
            
        }
    }
}
