{
    "Parameters": {
        "Protoplast_movement1": {
            "OutPlatetype":"pcrplate_skirted_riser",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"OutWell":"A1"
        },
		"Protoplast_movement2": {
            "OutPlatetype":"pcrplate_skirted_riser",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"OutWell":"A2"
        },
		"Protoplast_movement3": {
            "OutPlatetype":"pcrplate_skirted_riser",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"OutWell":"A3"
        },
		"Protoplast_movement4": {
            "OutPlatetype":"pcrplate_skirted_riser",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"OutWell":"A4"
        },
		"Protoplast_movement5": {
            "OutPlatetype":"pcrplate_skirted_riser",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"OutWell":"A5"
        },
		"Protoplast_movement6": {
            "OutPlatetype":"pcrplate_skirted_riser",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"OutWell":"A6"
        }
    }
}