{
    "Parameters": {
        "Protoplast_movement1": {
            "OutPlatetype":"pcrplate_skirted_riser",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"OutWell":"A1"
        }
    }
}