{
  "Parameters": {
    "MakePalette1": {
		"Imagefilename":"500x_darksidesmall.jpg",
		"Rotate": false,
		"AutoRotate": true,
		"PosterizeImage":false,
		"PosterizeLevels":2,
      "Cyan": "Cyan",
	"Magenta": "Magenta",
	"Yellow": "Yellow_ink",
	"Black": "Black",
      "OutPlate": "greiner384_riser",
	  "PalettePlate": "DWST12_riser",
      "VolumeForFullcolour": "1500ul"
    },
	"Pipette1": {
       "VolumePerWell": "20ul",
	   "Imagefilename":"500x_darksidesmall.jpg",
	   "OnlythisColour": "",
	   "NotthisColour": "",
	   "Rotate": false,
	   "AutoRotate": true,
	"PosterizeImage":false,
	"PosterizeLevels":2,
       "OutPlate": "greiner384_riser"
		}
  }
}


