{
  "Parameters": [{
    "Datacrunch": {
      "S": 0.5,
	  "Sunit": "M",
      "Km": 1,
	  "Kmunit": "M",
      "Vmax": 0.1,
      "Vmaxunit": "M/S",
      "Vunit": "M/S",
	  "SubstrateConc": 100g/l,
	  "SubstrateVol":"5ml",
	  "Substrate_name": "glucose",
	  "DNAConc": 1g/l,
	  "DNA_seq": "ATGAGCAAAGGAGAAGAACTTTTCACTGGAGTTGTCCCAATTCTTGTTGAATTAGATGGTGATGTTAATGGGCACAAATTTTCTGTCCGTGGAGAGGGTGAAGGTGATGCTACAAACGGAAAACTCACCCTTAAATTTATTTGCACTACTGGAAAACTACCTGTTCCATGGCCAACACTTGTCACTACTCTGACCTATGGTGTTCAATGCTTTTCCCGTTATCCGGATCACATGAAACGGCATGACTTTTTCAAGAGTGCCATGCCCGAAGGTTATGTACAGGAACGCACTATATCTTTCAAAGATGACGGGACCTACAAGACGCGTGCTGAAGTCAAGTTTGAAGGTGATACCCTTGTTAATCGTATCGAGTTAAAAGGTATTGATTTTAAAGAAGATGGAAACATTCTCGGACACAAACTCGAGTACAACTTTAACTCACACAATGTATACATCACGGCAGACAAACAAAAGAATGGAATCAAAGCTAACTTCAAAATTCGCCACAACGTTGAAGATGGTTCCGTTCAACTAGCAGACCATTATCAACAAAATACTCCAATTGGCGATGGCCCTGTCCTTTTACCAGACAACCATTACCTGTCGACACAATCTGTCCTTTCGAAAGATCCCAACGAAAAGCGTGACCACATGGTCCTTCTTGAGTTTGTAACTGCTGCTGGGATTACACATGGCATGGATGAGCTCTACAAAtaa",
	  "ProteinConc": 1g/l,
	  "Gene_name": "Superfolder GFP"
    }
  }],
  "Config": {
      "OUTPUT_COUNT": 1
  }
}
    