{
    "Parameters": {
        "Colony_PCR_3888": {
            "Additiveconc": "",
            "Additives": "",
            "AnnealingTemp": "",
            "Annealingtime": "",
            "Buffer": "",
            "DNTPS": "",
            "DNTPconc": "",
            "Denaturationtime": "",
            "Extensiontemp": "",
            "Extensiontime": "",
            "Finalextensiontime": "",
            "FwdPrimer": "",
            "FwdPrimerConc": "",
            "InitDenaturationtime": "",
            "Numberofcycles": "",
            "OutPlate": "",
            "PCRPolymerase": "",
            "ReactionVolume": "",
            "RevPrimer": "",
            "RevPrimerConc": "",
            "TargetpolymeraseConcentration": "",
            "Template": "",
            "Templatevolume": ""
        },
        "DNA_gel_1373": {
            "DNAgel": "",
            "DNAgelrunvolume": "",
            "InPlate": "",
            "Loadingdye": "",
            "Loadingdyeinsample": "",
            "Loadingdyevolume": "",
            "Mixingpolicy": "",
            "Samplenames": "",
            "Samplenumber": "",
            "Sampletotest": "",
            "Water": "",
            "Watervol": ""
        },
        "FindPartsthat_1017": {
            "OnlyreturnAvailableParts": "",
            "OnlyreturnWorkingparts": "",
            "Partdescriptions": "",
            "Parts": "",
            "Parttypes": ""
        },
        "FindPartsthat_6808": {
            "OnlyreturnAvailableParts": "",
            "OnlyreturnWorkingparts": "",
            "Partdescriptions": "",
            "Parts": "",
            "Parttypes": ""
        },
        "FindPartsthat_9134": {
            "OnlyreturnAvailableParts": "",
            "OnlyreturnWorkingparts": "",
            "Partdescriptions": "",
            "Parts": "",
            "Parttypes": ""
        },
        "FindPartsthat_9478": {
            "OnlyreturnAvailableParts": "",
            "OnlyreturnWorkingparts": "",
            "Partdescriptions": "",
            "Parts": "",
            "Parttypes": ""
        },
        "MoClo_design_9995": {
            "AssemblyStandard": "",
            "Constructname": "",
            "Level": "",
            "PartMoClotypesinorder": "",
            "Partsinorder": "",
            "Vector": ""
        },
        "Synthesis_3501": {
            "PartsWithOverhangs": ""
        },
        "Transformation_complete_1760": {
            "AgarPlate": "",
            "CompetentCells": "",
            "CompetentCellvolumeperassembly": "",
            "OutPlate": "",
            "Plateoutvolume": "",
            "Postplasmidtemp": "",
            "Postplasmidtime": "",
            "Preplasmidtemp": "",
            "Preplasmidtime": "",
            "Reaction": "",
            "Reactionvolume": "",
            "Recoverymedium": "",
            "Recoverytemp": "",
            "Recoverytime": "",
            "Recoveryvolume": ""
        },
        "TypeIISConstructAssemblyMMX_503": {
            "InactivationTemp": "",
            "InactivationTime": "",
            "MasterMix": "",
            "OutPlate": "",
            "OutputLocation": "",
            "OutputPlateNum": "",
            "OutputReactionName": "",
            "PartNames": "",
            "PartVols": "",
            "Parts": "",
            "ReactionTemp": "",
            "ReactionTime": "",
            "ReactionVolume": ""
        }
    }
}