{
"Parameters":
	{
        "LoadGel1":{
                "SampleName": "Marker",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
	},
	"LoadGel2":{
                "SampleName": "Lysate",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
	}, 
	"LoadGel3":{
                "SampleName": "Flowthrough",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
	},
	"LoadGel4":{
                "SampleName": "Wash1",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
	},
	"LoadGel5":{
                "SampleName": "Wash2",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
	},
        "LoadGel6":{
                "SampleName": "Wash3",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
        },
        "LoadGel7":{
                "SampleName": "Elution1",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
        },
        "LoadGel8":{
                "SampleName": "Elution2",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
        },
        "LoadGel9":{
                "SampleName": "Elution3",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
        },
        "LoadGel10":{
                "SampleName": "Elution4",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
        },
        "LoadGel11":{
                "SampleName": "Elution5",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
        },
        "LoadGel12":{
                "SampleName": "Elution6",
                "LoadVolume": "10ul",
                "Protein": "Load",
                "WaterName": "dH2O",
                "Water": "water",
                "WaterVolume": "10ul",
		            "GelPlate": "EPAGE48",
                "InPlate": "pcrplate_with_cooler"
        }	 	
}
}
