{
  "Parameters": {
    "PipetteImage": {
		"OnlythisColour":"",
		"Notthiscolour":"",
	  	"Imagefilename": "nyancat3.jpg",
		"Palettename":"ProteinPaintboxVisible",
      	"OutPlate": "greiner384_riser",
		"UVimage":false,
      	"VolumePerWell": "50ul"
    }
  }
}
