{
  "Parameters": {
    "PipetteImage": {
		"OnlythisColour":"",
		"Notthiscolour":"white",
	  	"Imagefilename": "ziggy5_384.jpg",
		"Palettename":"ProteinPaintboxSubset",
      	"OutPlate": "Agarplateforpicking384_riser",
		"UVimage":false,
      	"VolumePerWell": "5ul"
    }
  }
}
