{
  "Parameters": {
    "PipetteImage": {
		"OnlythisColour":"",
		"Notthiscolour":"white",
	  	"Imagefilename": "ziggy5_384.jpg",
		"Palettename":"ProteinPaintboxVisible",
		"Subset": true,
		"Subsetnames": [
		"DreidelTeal",
		"TinselPurple",
		"CupidPink",
		"LeorOrange"
		],
      	"OutPlate": "Agarplateforpicking384_riser",
		"UVimage":false,
      	"VolumePerWell": "2ul"
    }
  }
}
