{
  "Parameters": {
    "PipetteImage": {
		"OnlythisColour":"",
		"Notthiscolour":"verywhite",
	  	"Imagefilename": "ziggy5_384.jpg",
		"Rotate": false,
		"Palettename":"ProteinPaintboxVisible",
		"Subset": false,
		"Subsetnames": [
		"DreidelTeal",
		"TinselPurple",
		"CupidPink",
		"LeorOrange",
		"verywhite"
		],
      	"OutPlate": "Agarplateforpicking384_riser",
		"UVimage":false,
      	"VolumePerWell": "2ul"
    }
  }
}
