{
  "Parameters": {
    "PipetteImage": {
		"OnlythisColour":"",
		"Notthiscolour":"verywhite",
	  	"Imagefilename": "git.png",
		"Rotate": false,
		"AutoRotate": true,
		"Palettename":"ProteinPaintboxVisible",
		"Subset": true,
		"Subsetnames": [
		"DreidelTeal",
		"TinselPurple",
		"CupidPink",
		"LeorOrange",
		"verywhite",
		"E.coli",
		"E.coli pUC19 on sgal"
		],
      	"OutPlate": "Agarplateforpicking384_riser",
		"UVimage":false,
      	"VolumePerWell": "2ul"
    }
  }
}
