{
  "Parameters": {
    "PipetteImage": {
		"OnlythisColour":"",
		"Notthiscolour":"white",
	  	"Imagefilename": "41_3133-sgt-peppers4.jpg",
		"Rotate": false,
		"AutoRotate": true,
		"Palettename":"Neon",
		"Subset": true,
		"Subsetnames": [
				"blue",
				
				"yellow",
				"pink",
				
				"orange",
				"green",
				
				"red",
				"black",
				"white"
				],
		"UseLiquidClass":"paint",
      	"OutPlate": "greiner384_riser",
		"UVimage":false,
      	"VolumePerWell": "100ul"
    }
  }
}
