{
  "Parameters": {
    "PipetteImage": {
		"OnlythisColour":"",
		"Notthiscolour":"white",
	  	"Imagefilename": "ziggy5_384.jpg",
		"Palettename":"NewProteinPaintboxSubsetmap",
      	"OutPlate": "greiner384_riser",
		"UVimage":false,
      	"VolumePerWell": "100ul"
    }
  }
}
