{
  "Parameters": {
    "PipetteImage": {
	"OnlythisColour":"",
	  "Imagefilename": "omg.jpg",
		"Palettename":"ProteinPaintboxUV",
      "OutPlate": "greiner384_riser",
		"UVimage":true,
      "VolumePerWell": "50ul"
    }
  }
}


