{
    "Parameters": [
        {
            "Standarddigest_conc":{
                "ReactionVolume": "20ul",
                "DNAConc": "0.01g/l",
				"DNAMassperReaction": "0.0001mg",
				"DNAName":"vector1",
                "EnzymeNames" : [
                    "Nco1",
                ],
                "Water": "component:water",
                "DNASolution": "component:DNAsolution",
				"BSAoptional": "component:DNAsolution",
                "BSAvol": "0ul",
                "Buffer": "component:CutsmartBuffer",
                "BufferConcX": 10,
                "StockReConcinUperml":[
				 10000,
				],
				"DesiredConcinUperml":[
				 10,
				],
				"EnzSolutions":[
				"component:restrictionenzyme",
				],
                "OutPlate": "plate:pcrplate_with_cooler",
                "InPlate": "plate:pcrplate_with_cooler",
                "TipType": "tipbox:Gilson20",
                "ReactionTemp": "37C",
                "ReactionTime": "3600s",
                "InactivationTemp": "65C",
                "InactivationTime": "900s"
            }
    }],
    "Config": {
        "OUTPUT_COUNT": 1
    }
}
