{
    "Parameters": {
        "Standarddigest_conc": {
            "BSAoptional": "DNAsolution",
            "BSAvol": "0ul",
            "Buffer": "CutsmartBuffer",
            "BufferConcX": 10,
            "DNAConc": "50ng/ul",
            "DNAMassperReaction": "100ng",
            "DNAName": "vector2",
            "DNASolution": "DNAsolution",
            "DesiredConcinUperml": [
                10
            ],
            "EnzSolutions": [
                "restrictionenzyme"
            ],
            "EnzymeNames": [
                "Nco1"
            ],
            "InPlate": "pcrplate_with_cooler",
            "InactivationTemp": "65C",
            "InactivationTime": "900s",
            "OutPlate": "pcrplate_with_cooler",
            "ReactionTemp": "37C",
            "ReactionTime": "3600s",
            "ReactionVolume": "20ul",
            "StockReConcinUperml": [
                10000
            ],
            "Water": "water"
        }
    }
}
