{
    "Parameters": 
        {
            "Standarddigest_conc":{
                "ReactionVolume": "20ul",
                "DNAConc": "50ng/ul",
				"DNAMassperReaction": "100ng",
				"DNAName":"vector2",
                "EnzymeNames": [
                    "Nco1"
                ],
                "Water": "water",
                "DNASolution": "DNAsolution",
				"BSAoptional": "DNAsolution",
                "BSAvol": "0ul",
                "Buffer": "CutsmartBuffer",
                "BufferConcX": 10,
                "StockReConcinUperml":[
				 10000
				],
				"DesiredConcinUperml":[
				 10
				],
				"EnzSolutions":[
				"restrictionenzyme"
				],
                "OutPlate": "pcrplate_with_cooler",
                "InPlate": "pcrplate_with_cooler",
                "ReactionTemp": "37C",
                "ReactionTime": "3600s",
                "InactivationTemp": "65C",
                "InactivationTime": "900s"
            }
    }
}
