{
  "Parameters": [{
    "Aliquot": {
      "Solution": "component:PrimerFw",
      "Outplate": "plate:pcrplate_with_cooler",
      "TipType": "tipbox:Gilson20",
      "SolutionVolume": "100ul",
      "VolumePerAliquot": "10ul",
	"NumberofAliquots":3,
    }
  },
{
    "Aliquot": {
      "Solution": "component:PrimerRev",
      "Outplate": "plate:pcrplate_with_cooler",
      "TipType": "tipbox:Gilson20",
      "SolutionVolume": "100ul",
      "VolumePerAliquot": "10ul",
	"NumberofAliquots":3,
    }
  }],
  "Config": {
    "OUTPUT_COUNT": 6
  }
}