{
  "Parameters": {
    "AliquotParams1": {
      "Solution": "PrimerFw",
      "InPlate": "pcrplate_with_cooler",
      "OutPlate": "greiner384_riser",
      "SolutionVolume": "3100ul",
      "VolumePerAliquot": "10ul",
      "NumberofAliquots": 300
    },
    "AliquotParams2": {
      "Solution": "PrimerRev",
      "InPlate": "pcrplate_with_cooler",
      "OutPlate": "greiner384",
      "SolutionVolume": "100ul",
      "VolumePerAliquot": "20ul",
      "NumberofAliquots": 2
    }
  }
}
