{
  "Parameters": [{
    "Aliquot": {
      "Solution": "component:PrimerFw",
	  "InPlate": "plate:pcrplate_with_cooler",
      "Outplate": "plate:Kombi2mlEpp",
      "TipType": "tipbox:Gilson20",
      "SolutionVolume": "100ul",
      "VolumePerAliquot": "20ul",
	"NumberofAliquots":5,
    }
  },
{
    "Aliquot": {
      "Solution": "component:PrimerRev",
		"InPlate": "plate:pcrplate_with_cooler",
      "Outplate": "plate:Kombi2mlEpp",
      "TipType": "tipbox:Gilson20",
      "SolutionVolume": "100ul",
      "VolumePerAliquot": "20ul",
	"NumberofAliquots":0,
    }
  }],
  "Config": {
    "OUTPUT_COUNT": 5
  }
}