{
    "Parameters": {
        "AliquotParams1": {
            "InPlate": "pcrplate_with_cooler",
            "NumberofAliquots": 300,
            "OutPlate": "greiner384_riser",
            "Solution": "PrimerFw",
            "SolutionVolume": "3100ul",
            "VolumePerAliquot": "10ul"
        },
        "AliquotParams2": {
            "InPlate": "pcrplate_with_cooler",
            "NumberofAliquots": 2,
            "OutPlate": "greiner384",
            "Solution": "PrimerRev",
            "SolutionVolume": "100ul",
            "VolumePerAliquot": "20ul"
        }
    }
}
