{
  "Parameters": [{
    "AliquotParams": {
      "Solution": "component:PrimerFw",
	  "InPlate": "plate:pcrplate_with_cooler",
      "Outplate": "plate:greiner384_riser",
      "TipType": "tipbox:Gilson20",
      "SolutionVolume": "3100ul",
      "VolumePerAliquot": "10ul",
	"NumberofAliquots":300,
    }
  },
{
    "AliquotParams": {
      "Solution": "component:PrimerRev",
		"InPlate": "plate:pcrplate_with_cooler",
      "Outplate": "plate:greiner384",
      "TipType": "tipbox:Gilson20",
      "SolutionVolume": "100ul",
      "VolumePerAliquot": "20ul",
	"NumberofAliquots":2,
    }
  }],
  "Config": {
    "OUTPUT_COUNT": 302
  }
}