{
  "Parameters": [{
    "AliquotParams": {
      "Solution": "component:PrimerFw",
	  "InPlate": "plate:pcrplate_with_cooler",
      "Outplate": "plate:greiner384",
      "TipType": "tipbox:Gilson20",
      "SolutionVolume": "500ul",
      "VolumePerAliquot": "15ul",
	"NumberofAliquots":24,
    }
},
	{
    "AliquotParams": {
      "Solution": "component:PrimerRev",
		"InPlate": "plate:pcrplate_with_cooler",
      "Outplate": "plate:greiner384",
      "TipType": "tipbox:Gilson20",
      "SolutionVolume": "100ul",
      "VolumePerAliquot": "15ul",
	"NumberofAliquots":2,
    }
  }],
  "Config": {
    "OUTPUT_COUNT": 26
  }
}