{
    "Parameters":
        {
            "ConstructAssembly1":{
                "Parts": [
                    "dna_part",
                    "dna_part",
                    "dna_part"
                ],
                "ReactionVolume": "20ul",
                "PartVols": [
                    "3ul",
                    "3ul",
                    "3ul"
                ],
                "PartNames" : [
                    "dna1",
                    "dna2",
                    "dna3"
                ],
                "Water": "water",
                "Vector": "standard_cloning_vector_mark_1",
                "VectorVol": "3ul",
                "Buffer": "CutsmartBuffer",
                "BufferVol": "2ul",
                "Ligase": "T4Ligase",
                "LigVol": "1ul",
                "Atp": "ATP",
                "AtpVol": "1ul",
                "RestrictionEnzyme": "SapI",
                "ReVol": "1ul",
                "OutPlate": "pcrplate_with_cooler",
                "InPlate": "pcrplate_with_cooler",
                "ReactionTemp": "25C",
                "ReactionTime": "1800s",
                "InactivationTemp": "40C",
                "InactivationTime": "60s"
            },
            "ConstructAssembly2":{
                "Parts": [
                    "dna_part",
                    "dna_part",
                    "dna_part"
                ],
                "ReactionVolume": "20ul",
                "PartVols": [
                    "3ul",
                    "3ul",
                    "3ul"
                ],
                "PartNames" : [
                    "dna4",
                    "dna5",
                    "dna6"
                ],
                "Water": "water",
                "Vector": "standard_cloning_vector_mark_1",
                "VectorVol": "3ul",
                "Buffer": "CutsmartBuffer",
                "BufferVol": "2ul",
                "Ligase": "T4Ligase",
                "LigVol": "1ul",
                "Atp": "ATP",
                "AtpVol": "1ul",
                "RestrictionEnzyme": "SapI",
                "ReVol": "1ul",
                "OutPlate": "pcrplate_with_cooler",
                "InPlate": "pcrplate_with_cooler",
                "ReactionTemp": "25C",
                "ReactionTime": "1800s",
                "InactivationTemp": "40C",
                "InactivationTime": "60s"
            }
        }
}
