{
    "Parameters": {
        "ScreenAssemblyConditions": {
			"LHDOEFile":"8run4cpFactorial.xlsx",
			"DXORJMP":"JMP",
            "Replicates": 1,
			"OutputDesignFilename":"AssemblyDOE_test.xlsx",
            "ReactionTemp":"25C",
			"ReactionTime":"1800s",
			"OutputReactionName":"AssemblyDOE",
            "ReactionVolume": "20ul",
            "PartNamesArray": [ 
              [ "vector_1", "promoter_1", "rbs_1", "cds_1" ]
            ],
            "PartVolsArray": [
              [ "1ul", "1ul", "1ul", "1ul" ],
              [ "2ul", "1ul", "1ul", "1ul" ]
            ],
            "PartsArray": [
              [ "dna_part", "dna_part", "dna_part", "dna_part" ]
            ],
			"Mastermix":"mastermix_sapI",
			"OutPlate": "greiner384_riser"
        }
    }
}

