{
  "Parameters": {
    "Kla": {
      "Platetype": "24DSW_pyramid",
      "Liquid": "water",
      "Rpm": "200/min",
      "Shakertype": "Kuhner",
      "TargetRE": 226659.867,
      "Fillvolume": "1000ul",
      "D": 2.1e-9
    }
  }
}
