{
	"Parameters":{
    "TransformationControl": {
		"PlateWithCompetentCells":"pcrplate_with_cooler",
	 	"PlatewithRecoveryMedia":"pcrplate_skirted_riser",
		"CompetentCellPlateWells": [
			"F1",
			"F2", 
			"F3", 
			"F4",
			"F5"
	],
	  	"RecoveryPlateWells": 	[
			"F1",
			"F2", 
			"F3", 
			"F4",
			"F5"
	],
            
        	"RecoveryTemp":"37C",
	  	"RecoveryTime":"2h",
		"PostPlasmidTemp":"2C",
        	"PostPlasmidTime": "5min",
        	"Plasmid": "dna_part",
        	"ReactionVolume": "2ul",
		"CompetentCellTransferVolume": "21ul"
        }
  }
}
