{
  "Parameters": [{
    "LookUpMolecule": {
      "Compound":"Potassium Acetate",
      "Compoundlist": [
      "Water",
	  "Potassium Acetate",
	  "Tris Acetate",
	  "Magnesium Acetate",
	"Paclitaxel"
	  ],
    }
  }],
    "Config": {
        "OUTPUT_COUNT": 1
    }
}
