{
  "Parameters": {
    "Mastermix": {
      "Buffer": "water",
	"OtherComponents": [
	"CutsmartBuffer",
	"T4Ligase",
	"SapI",
	"ATP"
	],
	"Inplate":"Kombi2mlEpp",
      "OutPlate": "pcrplate_with_cooler",
      "TotalVolumeperMastermix": "200ul",
      "OtherComponentVolumes": [
	"20ul",
	"10ul",
	"10ul",
	"10ul"
	],
	"NumberofMastermixes":3,
	"AliquotbyRow":false
    }
  }
}
