{
    "Parameters": {
        "ConstructAssembly_sim":{
            "Parts": [
                "dna_part",
                "dna_part"
            ],
            "ReactionVolume": "20ul",
            "PartVols": [
                "1ul",
                "1ul"
            ],
			"PartConcs": [
			"0.1g/l",
			"0.11g/l"
			],
            "Partsinorder" : [
                "Part1",
                "Part2"
            ],
			"Vectordata":"Vector1",
			"Constructname": "MyfavouriteConstruct",
            "Water": "water",
            "Vector": "standard_cloning_vector_mark_1",
            "VectorVol": "3ul",
			"VectorConcentration": "0.01M/l",
            "Buffer": "CutsmartBuffer",
            "BufferVol": "2ul",
            "Ligase": "T4Ligase",
            "LigVol": "1ul",
            "Atp": "ATP",
            "AtpVol": "1ul",
            "RestrictionEnzyme": "SapI",
            "ReVol": "1ul",
            "OutPlate": "pcrplate_with_cooler",
            "InPlate": "pcrplate_with_cooler",
            "ReactionTemp": "25C",
            "ReactionTime": "1800s",
            "InactivationTemp": "40C",
            "InactivationTime": "60s"
        }
    }
}
