{
    "Parameters": 
        {
            "Standarddigestparams":{
                "ReactionVolume": "20ul",
                "DNAVol": "1ul",
				"DNAName":"vector1",
                "EnzymeNames" : [
                    "Nco1"
                ],
                "Water": "water",
                "DNASolution": "DNAsolution",
				"BSAoptional": "DNAsolution",
                "BSAvol": "0ul",
                "Buffer": "CutsmartBuffer",
                "BufferVol": "2ul",
                "EnzVolumestoadd":[
				 "1ul"
				],
				"EnzSolutions":[
				"restrictionenzyme"
				],
                "OutPlate": "pcrplate_with_cooler",
                "InPlate": "pcrplate_with_cooler",
                "ReactionTemp": "37C",
                "ReactionTime": "3600s",
                "InactivationTemp": "65C",
                "InactivationTime": "10s"
            }
    }
}
