{
    "Parameters": {
        "PCR": {
			"Projectname": "AssemblyRefactored",
			"MasterMixtype": "mastermix_sapI",
			"LHPolicyName": "dna",
			"OutPlate": "pcrplate_skirted_riser",
      		"OutputPlateNum": 1,
			"EnzymeName": "sapi",
      		"Watertype": "water",
			"Reactiontopartseqs": {
				"Assembly1": [
					"ACGTACGT",
					"ACGTACGT",
					"ACGTACGT"
                ],
                "Assembly2": [
					"ACGTACGT",
					"ACGTACGT",
					"ACGTACGT"
                ],
                "Assembly3": [
					"ACGTACGT",
					"ACGTACGT",
					"ACGTACGT"
                ],
                "Assembly4": [
					"ACGTACGT",
					"ACGTACGT",
					"ACGTACGT"
                ]
			},
			"Reactiontoassemblyparts": {
                "Assembly1": [
					"Part1",
					"Part2",
					"Part3"
                ],
                "Assembly2": [
					"Part1",
					"Part2",
					"Part3"
                ],
                "Assembly3": [
					"Part1",
					"Part2",
					"Part3"
                ],
                "Assembly4": [
					"Part1",
					"Part2",
					"Part3"
                ]
            },
            "Reactiontopartvolumes": {
                "Assembly1":[
					"1",
					"1",
					"1"
				],
                "Assembly2":[
					"1",
					"1",
					"1"
				],
                "Assembly3": [
					"1",
					"1",
					"1"
				],
                "Assembly4": [
					"1",
					"1",
					"1"
				]
            },
			"Reactiontoparttypes": {
                "Assembly1":[
					"dna_parts",
					"dna_parts",
					"dna_parts"
				],
                "Assembly2":[
					"dna_parts",
					"dna_parts",
					"dna_parts"
				],
                "Assembly3": [
					"dna_parts",
					"dna_parts",
					"dna_parts"
				],
                "Assembly4": [
					"dna_parts",
					"dna_parts",
					"dna_parts"
				]  
            },
			"Reactiontonames": {
                "Assembly1": "Assembly1",
                "Assembly2": "Assembly2",
                "Assembly3": "Assembly3",
                "Assembly4": "Assembly4"
            }
        }
    }
}
