{
  "Parameters": {
    "PCR": {
      "Additives": [
      ],
      "FwdPrimer": "PrimerFw",
      "RevPrimer": "PrimerRev",
      "PCRPolymerase": "Q5Polymerase",
	  "DNTPS":"DNTPs",
	  "DNTPconc":"0.0001g/l",
      "Buffer": "HC",
      "Template": "pET_GFP",
      "OutPlate": "pcrplate_with_cooler",
      "ReactionVolume": "20ul",
      "FwdPrimerConc": "0.0001g/l",
      "RevPrimerConc": "0.0001g/l",
      "Templatevolume": "2ul",
      "Additiveconc": "0.0001g/l",
      "Numberofcycles": 25,
      "InitDenaturationtime": "30s",
      "Denaturationtime": "5s",
      "Annealingtime": "10s",
      "AnnealingTemp": "60˚C",
      "Extensiontime": "60s",
      "Extensiontemp": "72˚C",
      "TargetpolymeraseConcentration": "0.0001g/l",
      "Finalextensiontime": "600s"
    }
  }
}
