{
    "Parameters": {
        "PCR": {
            "Additiveconc": "0.0001g/l",
            "Additives": [],
            "AnnealingTemp": "60C",
            "Annealingtime": "10s",
            "Buffer": "Q5buffer",
            "DNTPS": "DNTPs",
            "DNTPconc": "0.0001g/l",
            "Denaturationtime": "5s",
            "Extensiontemp": "72\u02daC",
            "Extensiontime": "60s",
            "Finalextensiontime": "600s",
            "FwdPrimer": "PrimerFw",
            "FwdPrimerConc": "0.0001g/l",
            "InitDenaturationtime": "30s",
            "Numberofcycles": 25,
            "OutPlate": "pcrplate_with_cooler",
            "PCRPolymerase": "Q5Polymerase",
            "ReactionVolume": "20ul",
            "RevPrimer": "PrimerRev",
            "RevPrimerConc": "0.0001g/l",
            "TargetpolymeraseConcentration": "0.0001g/l",
            "Template": "pET_GFP",
            "Templatevolume": "2ul"
        }
    }
}
