{
    "Parameters": {
        "MakeAssemblies": {
            "Atp": "ATP",
            "AtpVol": "1ul",
            "Buffer": "CutsmartBuffer",
            "BufferVol": "2ul",
            "InPlate": "pcrplate_with_cooler",
            "InactivationTemp": "40C",
            "InactivationTime": "60s",
            "LigVol": "1ul",
            "Ligase": "T4Ligase",
            "OutPlate": "pcrplate_with_cooler",
            "PartNames": [ 
              [ "vector_1", "promoter_1", "rbs_1", "cds_1" ],
              [ "vector_1", "promoter_1", "rbs_1", "cds_1" ],
              [ "vector_1", "promoter_1", "rbs_1", "cds_1" ],
              [ "vector_1", "promoter_1", "rbs_1", "cds_1" ]
            ],
            "PartVols": [
              [ "1ul", "1ul", "1ul", "1ul" ],
              [ "1ul", "1ul", "1ul", "1ul" ],
              [ "1ul", "1ul", "1ul", "1ul" ],
              [ "1ul", "1ul", "1ul", "1ul" ]
            ],
            "Parts": [
              [ "dna_part", "dna_part", "dna_part", "dna_part" ],
              [ "dna_part", "dna_part", "dna_part", "dna_part" ],
              [ "dna_part", "dna_part", "dna_part", "dna_part" ],
              [ "dna_part", "dna_part", "dna_part", "dna_part" ]
            ],
            "ReVol": "1ul",
            "ReactionTemp": "25C",
            "ReactionTime": "1800s",
            "ReactionVolume": "20ul",
            "RestrictionEnzyme": "SapI",
            "Vector": "standard_cloning_vector_mark_1",
            "VectorVol": "3ul",
            "Water": "water"
        }
    }
}
