{
    "Parameters": {
        "gelof1stpcrstep": {
            "DNAgel": "EGEL96_1",
            "DNAgelrunvolume": "15ul",
            "Ladder": "1kb DNA Ladder"
			,
            "Loadingdye": "blue",
            "Loadingdyeinsample": true,
            "Loadingdyevolume": "1ul",
            "MixPlate": "pcrplate_skirted_riser",
            "Mixingpolicy": "dna",
            "ProjectName": "PCRAssembleandRun",
            "Samplenames": [
                "lefthomologyarm1kb",
                "lefthomologyarm3kb",
                "lefthomologyarm2.5kbA",
                "lefthomologyarm2.5kbB",
                "righthomologyarm1kb",
                "righthomologyarm3kb",
                "righthomologyarm2.5kbA",
                "righthomologyarm2.5kbB"
            ],
            "Samplenumber": 1,
            "Sampletotest": "dna_part",
            "Water": "water",
            "Watervol": "10ul"
        }
    }
}
