
{
    "Parameters": {
        "BothPrimersOri": {
					"RegionSequenceString":"ctagcgtttgcaatgcaccaggtcatcattgacccaggcgtgttccaccaggccgctgcctcgcaactcttcgcaggcttcgccgacctgctcgcgccacttcttcacgcgggtggaatccgatccgcacatgaggcggaaggtttccagcttgagcgggtacggctcccggtgcgagctgaaatagtcgaacatccgtcgggccgtcggcgacagcttgcggtacttctcccatatgaatttcgtgtagtggtcgccagcaaacagcacgacgatttcctcgtcgatcaggacctggcaacgggacgttttcttgccacggtccaggacgcggaagcggtgcagcagcgacaccgattccaggtgcccaacgcggtcggacgtgaagcccatcgccgtcgcctgtaggcgcgacaggcattcctcggccttcgtgtaataccggccattgatcgaccagcccaggtcctggcaaagctcgtagaacgtgaaggtgatcggctcgccgataggggtgcgcttcgcgtactccaacacctgctgccacaccagttcgtcatcgtcggcccgcagctcgacgccggtgtaggtgatcttcacgtccttgttgacgtggaaaatgaccttgttttgcagcgcctcgcgcgggattttcttgttgcgcgtggtgaacagggcagagcgggccgtgtcgtttggcatcgctcgcatcgtgtccggccacggcgcaatatcgaacaaggaaagctgcatttccttgatctgctgcttcgtgtgtttcagcaacgcggcctgcttggcttcgctgacctgttttgccaggtcctcgccggcggtttttcgcttcttggtcgtcatagttcctcgcgtgtcgatggtcatcgacttcgccaaacctgccgcctcctgttcgagacgacgcgaacgctccacggcggccgatggcgcgggcagggcagggggagccagttgcacgctgtcgcgctcgatcttggccgtagcttgctggactatcgagccgacggactggaaggtttcgcggggcgcacgcatgacggtgcggcttgcgatggtttcggcatcctcggcggaaaaccccgcgtcgatcagttcttgcctgtatgccttccggtcaaacgtccgattcat",
					"FlankTargetSequence":true,
		            "DNASeqfile": "pSEVA521.gb",
					"Plasmid":true,
		            "Maxtemp": "65C",
		            "Mintemp": "50C",
		            "Maxgc": 0.6,
		            "Minlength": 18,
					"Maxlength":30,
					"Seqstoavoid":[
					""
					],
					"PermittednucleotideOverlapBetweenPrimers": 10
        },
        "BothPrimersTetA": {
					"RegionSequenceString":"atgccggtactgccgggcctcttgcgggatatcgtccattccgacagcatcgccagtcactatggcgtgctgctagcgctatatgcgttgatgcaatttctatgcgcacccgttctcggagcactgtccgaccgctttggccgccgcccagtcctgctcgcttcgctacttggagccactatcgactacgcgatcatggcgaccacacccgtcctgtggattctctacgccggacgcatcgtggccggcatcaccggcgccacaggtgcggttgctggcgcctatatcgccgacatcaccgatggggaagatcgggctcgccacttcgggctcatgagcgcttgtttcggcgtgggtatggtggcaggccccgtggccgggggactgttgggcgccatctccctgcacgcaccattccttgcggcggcggtgctcaacggcctcaacctactactgggctgcttcctaatgcaggagtcgcataagggagagcgccgtccgatgcccttgagagccttcaacccagtcagctccttccggtgggcgcggggcatgaccattgtggccgcacttatgactgtcttctttatcatgcaactcgtaggacaggtgccggcagcgctctgggtcattttcggcgaggaccgctttcgctggagcgcgacgatgatcggcctgtcgcttgcggtattcggaatcttgcacgccctcgctcaagccttcgtcactggtcccgccaccaaacgtttcggcgagaagcaggccattatcgccggcatggcggccgacgcgctgggctacgtcttgctggcgttcgcgacgcgaggctggatggccttccccattatgattcttctcgcttccggcggcatcgggatgcccgcgttgcaggccatgctgtccaggcaggtagatgacgaccatcagggacagcttcaaggatcgctcgcggctcttaccagcctaacttcgatcactggaccgctgatcgtcacggcgatttatgccgcctcggcgagcacatggaacgggttggcatggattgtaggcgccgccctataccttgtctgcctccccgcgttgcgtcgcggtgcatggagccgggccacctcgacctga",
					"FlankTargetSequence":true,
		            "DNASeqfile": "pSEVA521.gb",
					"Plasmid":true,
		            "Maxtemp": "65C",
		            "Mintemp": "50C",
		            "Maxgc": 0.6,
		            "Minlength": 18,
					"Maxlength":30,
					"Seqstoavoid":[
					""
					],
					"PermittednucleotideOverlapBetweenPrimers": 10
        },
		"BothPrimersOriRevComp":{
							"RegionSequenceString":"atgaatcggacgtttgaccggaaggcatacaggcaagaactgatcgacgcggggttttccgccgaggatgccgaaaccatcgcaagccgcaccgtcatgcgtgcgccccgcgaaaccttccagtccgtcggctcgatagtccagcaagctacggccaagatcgagcgcgacagcgtgcaactggctccccctgccctgcccgcgccatcggccgccgtggagcgttcgcgtcgtctcgaacaggaggcggcaggtttggcgaagtcgatgaccatcgacacgcgaggaactatgacgaccaagaagcgaaaaaccgccggcgaggacctggcaaaacaggtcagcgaagccaagcaggccgcgttgctgaaacacacgaagcagcagatcaaggaaatgcagctttccttgttcgatattgcgccgtggccggacacgatgcgagcgatgccaaacgacacggcccgctctgccctgttcaccacgcgcaacaagaaaatcccgcgcgaggcgctgcaaaacaaggtcattttccacgtcaacaaggacgtgaagatcacctacaccggcgtcgagctgcgggccgacgatgacgaactggtgtggcagcaggtgttggagtacgcgaagcgcacccctatcggcgagccgatcaccttcacgttctacgagctttgccaggacctgggctggtcgatcaatggccggtattacacgaaggccgaggaatgcctgtcgcgcctacaggcgacggcgatgggcttcacgtccgaccgcgttgggcacctggaatcggtgtcgctgctgcaccgcttccgcgtcctggaccgtggcaagaaaacgtcccgttgccaggtcctgatcgacgaggaaatcgtcgtgctgtttgctggcgaccactacacgaaattcatatgggagaagtaccgcaagctgtcgccgacggcccgacggatgttcgactatttcagctcgcaccgggagccgtacccgctcaagctggaaaccttccgcctcatgtgcggatcggattccacccgcgtgaagaagtggcgcgagcaggtcggcgaagcctgcgaagagttgcgaggcagcggcctggtggaacacgcctgggtcaatgatgacctggtgcattgcaaacgctag",
							"FlankTargetSequence":true,
				            "DNASeqfile": "pSEVA521.gb",
							"Plasmid":true,
				            "Maxtemp": "65C",
				            "Mintemp": "50C",
				            "Maxgc": 0.6,
				            "Minlength": 18,
							"Maxlength":30,
							"Seqstoavoid":[
							""
							],
							"PermittednucleotideOverlapBetweenPrimers": 10
		        }
    }
}

