{
    "Parameters": {
        "newparams": {
            "LiquidVolumes": ["19ul","100ul"],
            "Liquidname": "tartrazine",
            "OutPlates": [
            "pcrplate_skirted_riser20",
			"pcrplate_skirted_riser40"
            ],
            "LiquidTypes": ["water","PostMix","PreMix", "DispenseAboveLiquid"],
            "Startingsolution": "tartrazine",
           
			"TestName":"Test"
        }
    }
}
