{
    "Parameters": {
        "newparams": {
            "LiquidVolumes": ["1ul","21ul"],
            "Liquidname": "Evian",
            "OutPlates": [
            "pcrplate_skirted_riser40",
            "pcrplate_with_cooler"
            ],
            "LiquidTypes": ["water","dna_mix","dna","PostMix"],
            "Startingsolution": "water",
            "WellsUsedperOutPlateInorder":[0,0,0]
        }
    }
}
