{
    "Parameters": {
        "newparams": {
            "LiquidVolumes": ["19ul","100ul"],
            "Liquidname": "tartrazine",
            "OutPlates": [
			
            "pcrplate_skirted_riser20",
			"greiner384_riser20",
			"DSW96_riser20",
            ],
            "LiquidTypes": ["water","NeedToMix", "DispenseAboveLiquid"],
            "Startingsolution": "tartrazine",
           
			"TestName":"ddeploy"
        }
    }
}
