{
    "Parameters": {
        "newparams": {
            "LiquidVolumes": ["19ul","100ul"],
            "Liquidname": "tartrazine",
            "OutPlates": [
            "pcrplate_skirted_riser40"
            ],
            "LiquidTypes": ["water","dna_mix","DispenseAboveLiquid"],
            "Startingsolution": "tartrazine",
            "WellsUsedperOutPlateInorder":[0]
        }
    }
}
