{
    "Parameters": {
        "InitialGrowth1": {
            "Growthtemp": "25C",
            "Growthtime": "3600s",
            "ShakingSpeed": "800/min"
        },
        "MediaPrep1": {
            "YeastExtractConc": "30g/l",
            "TryptoneConc": "18g/l",
            "GlycerolConc": "2g/l",
            "TotalVolume": "480ul",
            "OutputPlateType": "DSW96",
            "YeastExtract": "Yeast extract",
            "Tryptone": "Tryptone",
            "Glycerol": "Glycerol",
            "BaseMedium": "LB"
        },
        "InoculateInitialGrowth1": {
            "InoculumVolume": "20ul",
            "Inoculum": "culture",
            "Medium": "TB"
        },
        "InoculateOvernightGrowth1": {
            "InoculumVolume": "20ul"
        },
        "OverNightGrowth1": {
            "Growthtemp": "25C",
            "Growthtime": "86400s",
            "ShakingSpeed": "800/min"
        },
        "Split1": {
            "Stream1Vol": "50ul",
            "Stream2Vol": "50ul",
            "Stream1PlateType": "greinerfb96",
            "Stream2PlateType": "greinerfb96"
        },
        "ProductAssay1": {
            "ExcitationWavelength": "300nm",
            "EmissionWavelength": "450nm",
            "DilutionVolume": "150ul",
            "Diluent": "water"
        },
        "ODAssay1": {
            "AbsorbanceWavelength": "600nm",
            "DilutionVolume": "150ul",
            "Diluent": "water"
        }
    },
    "Config": {
        "InputPlateType": [
            "pcrplate_skirted_riser"
        ],
        "OutputPlateType": [
            "pcrplate_skirted_riser"
        ]
    }
}