{
  "Parameters": [{
    "Mastermix_reaction": {
      "TopUpBuffer": "component:water",
	"Components": [
	"component:CutsmartBuffer",
	"component:T4Ligase",
	"component:SapI",
	"component:ATP"
	],
	"Inplate":"plate:Kombi2mlEpp",
      "Outplate": "plate:pcrplate_with_cooler",
      "TipType": "tipbox:Gilson200",
      "TotalVolumeperreaction": "20ul",
	"VolumetoLeaveforDNAperreaction":"5ul",
      "ComponentVolumesperReaction": [
	"2ul",
	"1ul",
	"1ul",
	"1ul"
	],
	"NumberofMastermixes":1,
	"Reactionspermastermix":10,
	"AliquotbyRow":false
    }
  }],
  "Config": {
    "OUTPUT_COUNT": 1
  }
}