{
  "Parameters": {
    "Mastermix_reaction": {
      "TopUpBuffer": "water",
	"Components": [
	"CutsmartBuffer",
	"T4Ligase",
	"SapI",
	"ATP"
	],
	"Inplate":"Kombi2mlEpp",
      "OutPlate": "pcrplate_with_cooler",
      "TotalVolumeperreaction": "20ul",
	"VolumetoLeaveforDNAperreaction":"5ul",
      "ComponentVolumesperReaction": [
	"2ul",
	"1ul",
	"1ul",
	"1ul"
	],
	"NumberofMastermixes":1,
	"Reactionspermastermix":10,
	"AliquotbyRow":false
    }
  }
}
