{
    "Parameters": {
        "Assembly": {
			"Projectname": "AssemblyRefactored",
			"MasterMixtype": "mastermix_sapI",
			"LHPolicyName": "dna",
			"OutPlate": "pcrplate_skirted_riser",
      		"OutputPlateNum": 1,
			"EnzymeName": "sapi",
      		"Watertype": "water",
			"Reactiontopartseqs": {
				"Assembly1": [
               
                {
                    "jm": "rbs_1",
                    "seq": "GCTCTTCAGACTTCACCTAGTCGACATGACTAGGCCTCTGAGCTTTCTCTAGAAATTGGTGTTTGGCAGTCACAAAACCGCAATAGTATGACTCCACGAGGAAAATGTTACTCCCACGTTTCACTTGCACATTGTCGCTGAAGAGC"
                },
                {
                    "jm": "cds_1",
                    "seq": "GCTCTTCACGCGATTCTGACTGACCCGGGAACTCACCTCCACACCCGTTGCTTACGGGACAGCCAGAATATTTAAGGATGTCGAGCACTACCCCAGCCAAAATACTTGCTCTAATCAATTGGACGGCGGCGCGAAGGAGGAATTTTGAAGAGC"
                },
                {
                    "jm": "Vector",
                    "seq": "GCTCTTCATTTGTACTCACCTTCAGTCTCAGTGCAGCGGGGCTAATCGTAATTTTCATCCTTGATCGGTACCTAGGAACGGTATACGGGAAATACGTTAGGGCTCGCGGACAAAACATCCCTGGGCATCTAAGTGGATCCACCCCTCGTGGATTAGCTTTCGATGTGACAACCTACCACCACCTTCATCCTCTCGCTGGTGCTGGCACAGCATATGTCGGTGATTCAGTTGTGGCGACTGATGGATCTACACGCTCCAGGGGGGGTGGGCTTCCATAAAAAAGGAGCGGGGGAATTTATCCTGGAACACCGCACAGGGCCTGCGCGACGGAGATCGAGTTTTTTCAAGCCGGAATGTTAAACGCCCACCCACGTGTATAAATTAATGAGCAAGATCTCGCTCTGTTAACGGTGAAAATGATTAGCAGGAAGGCATAAATGTGTAGTGGAAGCACGGGGTGTATATAGGTACAGATTACATGCCAACCTCTGGTTGGAACTGTTTGAAGATGGGTTGTAAGATACATGGGGGCTTGCGGACGTGGGAGCCATCAGGAATACCGCGATCACTACGACCACAGTAGTGAAGAGC"
                }
            ],
                "Assembly2": [
               
                {
                    "jm": "rbs_1",
                    "seq": "GCTCTTCAGACTTCACCTAGTCGACATGACTAGGCCTCTGAGCTTTCTCTAGAAATTGGTGTTTGGCAGTCACAAAACCGCAATAGTATGACTCCACGAGGAAAATGTTACTCCCACGTTTCACTTGCACATTGTCGCTGAAGAGC"
                },
                {
                    "jm": "cds_1",
                    "seq": "GCTCTTCACGCGATTCTGACTGACCCGGGAACTCACCTCCACACCCGTTGCTTACGGGACAGCCAGAATATTTAAGGATGTCGAGCACTACCCCAGCCAAAATACTTGCTCTAATCAATTGGACGGCGGCGCGAAGGAGGAATTTTGAAGAGC"
                },
                {
                    "jm": "Vector",
                    "seq": "GCTCTTCATTTGTACTCACCTTCAGTCTCAGTGCAGCGGGGCTAATCGTAATTTTCATCCTTGATCGGTACCTAGGAACGGTATACGGGAAATACGTTAGGGCTCGCGGACAAAACATCCCTGGGCATCTAAGTGGATCCACCCCTCGTGGATTAGCTTTCGATGTGACAACCTACCACCACCTTCATCCTCTCGCTGGTGCTGGCACAGCATATGTCGGTGATTCAGTTGTGGCGACTGATGGATCTACACGCTCCAGGGGGGGTGGGCTTCCATAAAAAAGGAGCGGGGGAATTTATCCTGGAACACCGCACAGGGCCTGCGCGACGGAGATCGAGTTTTTTCAAGCCGGAATGTTAAACGCCCACCCACGTGTATAAATTAATGAGCAAGATCTCGCTCTGTTAACGGTGAAAATGATTAGCAGGAAGGCATAAATGTGTAGTGGAAGCACGGGGTGTATATAGGTACAGATTACATGCCAACCTCTGGTTGGAACTGTTTGAAGATGGGTTGTAAGATACATGGGGGCTTGCGGACGTGGGAGCCATCAGGAATACCGCGATCACTACGACCACAGTAGTGAAGAGC"
                }
            ],
                "Assembly3": [
              
                {
                    "jm": "rbs_1",
                    "seq": "GCTCTTCAGACTTCACCTAGTCGACATGACTAGGCCTCTGAGCTTTCTCTAGAAATTGGTGTTTGGCAGTCACAAAACCGCAATAGTATGACTCCACGAGGAAAATGTTACTCCCACGTTTCACTTGCACATTGTCGCTGAAGAGC"
                },
                {
                    "jm": "cds_1",
                    "seq": "GCTCTTCACGCGATTCTGACTGACCCGGGAACTCACCTCCACACCCGTTGCTTACGGGACAGCCAGAATATTTAAGGATGTCGAGCACTACCCCAGCCAAAATACTTGCTCTAATCAATTGGACGGCGGCGCGAAGGAGGAATTTTGAAGAGC"
                },
                {
                    "jm": "Vector",
                    "seq": "GCTCTTCATTTGTACTCACCTTCAGTCTCAGTGCAGCGGGGCTAATCGTAATTTTCATCCTTGATCGGTACCTAGGAACGGTATACGGGAAATACGTTAGGGCTCGCGGACAAAACATCCCTGGGCATCTAAGTGGATCCACCCCTCGTGGATTAGCTTTCGATGTGACAACCTACCACCACCTTCATCCTCTCGCTGGTGCTGGCACAGCATATGTCGGTGATTCAGTTGTGGCGACTGATGGATCTACACGCTCCAGGGGGGGTGGGCTTCCATAAAAAAGGAGCGGGGGAATTTATCCTGGAACACCGCACAGGGCCTGCGCGACGGAGATCGAGTTTTTTCAAGCCGGAATGTTAAACGCCCACCCACGTGTATAAATTAATGAGCAAGATCTCGCTCTGTTAACGGTGAAAATGATTAGCAGGAAGGCATAAATGTGTAGTGGAAGCACGGGGTGTATATAGGTACAGATTACATGCCAACCTCTGGTTGGAACTGTTTGAAGATGGGTTGTAAGATACATGGGGGCTTGCGGACGTGGGAGCCATCAGGAATACCGCGATCACTACGACCACAGTAGTGAAGAGC"
                }
            ],
                "Assembly4": [
                
                {
                    "jm": "rbs_1",
                    "seq": "GCTCTTCAGACTTCACCTAGTCGACATGACTAGGCCTCTGAGCTTTCTCTAGAAATTGGTGTTTGGCAGTCACAAAACCGCAATAGTATGACTCCACGAGGAAAATGTTACTCCCACGTTTCACTTGCACATTGTCGCTGAAGAGC"
                },
                {
                    "jm": "cds_1",
                    "seq": "GCTCTTCACGCGATTCTGACTGACCCGGGAACTCACCTCCACACCCGTTGCTTACGGGACAGCCAGAATATTTAAGGATGTCGAGCACTACCCCAGCCAAAATACTTGCTCTAATCAATTGGACGGCGGCGCGAAGGAGGAATTTTGAAGAGC"
                },
                {
                    "jm": "Vector",
                    "seq": "GCTCTTCATTTGTACTCACCTTCAGTCTCAGTGCAGCGGGGCTAATCGTAATTTTCATCCTTGATCGGTACCTAGGAACGGTATACGGGAAATACGTTAGGGCTCGCGGACAAAACATCCCTGGGCATCTAAGTGGATCCACCCCTCGTGGATTAGCTTTCGATGTGACAACCTACCACCACCTTCATCCTCTCGCTGGTGCTGGCACAGCATATGTCGGTGATTCAGTTGTGGCGACTGATGGATCTACACGCTCCAGGGGGGGTGGGCTTCCATAAAAAAGGAGCGGGGGAATTTATCCTGGAACACCGCACAGGGCCTGCGCGACGGAGATCGAGTTTTTTCAAGCCGGAATGTTAAACGCCCACCCACGTGTATAAATTAATGAGCAAGATCTCGCTCTGTTAACGGTGAAAATGATTAGCAGGAAGGCATAAATGTGTAGTGGAAGCACGGGGTGTATATAGGTACAGATTACATGCCAACCTCTGGTTGGAACTGTTTGAAGATGGGTTGTAAGATACATGGGGGCTTGCGGACGTGGGAGCCATCAGGAATACCGCGATCACTACGACCACAGTAGTGAAGAGC"
                }
            ]
			},
			"Reactiontoassemblyparts": {
                "Assembly1": [
					"Part1",
					"Part2",
					"Part3"
                ],
                "Assembly2": [
					"Part1",
					"Part2",
					"Part3"
                ],
                "Assembly3": [
					"Part1",
					"Part2",
					"Part3"
                ],
                "Assembly4": [
					"Part1",
					"Part2",
					"Part3"
                ]
            },
            "Reactiontoassemblyvolumes": {
                "Assembly1":[
					"1ul",
					"1ul",
					"1ul"
				],
                "Assembly2":[
					"1ul",
					"1ul",
					"1ul"
				],
                "Assembly3": [
					"1ul",
					"1ul",
					"1ul"
				],
                "Assembly4": [
					"1ul",
					"1ul",
					"1ul"
				]
            },
			"Reactiontoparttypes": {
                "Assembly1":[
					"dna_part",
					"dna_part",
					"dna_part"
				],
                "Assembly2":[
					"dna_part",
					"dna_part",
					"dna_part"
				],
                "Assembly3": [
					"dna_part",
					"dna_part",
					"dna_part"
				],
                "Assembly4": [
					"dna_part",
					"dna_part",
					"dna_part"
				]  
            },
			"Reactiontonames": {
                "Assembly1": "Assembly1",
                "Assembly2": "Assembly2",
                "Assembly3": "Assembly3",
                "Assembly4": "Assembly4"
            }
        }
    }
}
