{
    "Parameters": {
        "AliquotParams": {
            "InPlate": "pcrplate_with_cooler",
            "NumberofAliquots": 50,
            "OutPlate": "pcrplate_with_cooler",
            "Solution": "PrimerFw",
            "SolutionVolume": "4000ul",
            "VolumePerAliquot": "10ul"
        }
    }
}
