{
  "Parameters": {
    "AliquotParams": {
      "Solution": "PrimerFw",
      "InPlate": "pcrplate_with_cooler",
      "OutPlate": "pcrplate_with_cooler",
      "SolutionVolume": "4000ul",
      "VolumePerAliquot": "10ul",
      "NumberofAliquots": 50
    }
  }
}
