{
    "Parameters": {
        "AliquotParams": {
            "NumberofAliquots": 160,
            "OutPlate": "nunc1536_riser",
            "Solutions": [
			"water",
			"fluorescein"
			],
			"ByRow": false,
            "SolutionVolume": "4000ul",
            "VolumePerAliquot": "5ul"
        }
    }
}
