{
    "Parameters": {
        "AliquotParams": {
            "InPlate": "pcrplate_with_cooler",
            "NumberofAliquots": 16,
            "OutPlate": "pcrplate_with_cooler",
            "Solutions": [
			"water",
			"fluorescein"
			],
			"ByRow": false,
            "SolutionVolume": "4000ul",
            "VolumePerAliquot": "25ul"
        }
    }
}
