{
    "Parameters": {
        "Protoplast_movement_overlay1": {
            "OutPlatetype":"pcrplate_skirted_riser",
			"OutPlatetype2":"pcrplate_with_incubater",
			"AgarPlate":"falcon6wellAgar",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"Plateoutvolume":"50ul",
			"TransformedCellsVol":"190ul",
			"OutWell":"A1",
			"OutWell2":"A1"
        },
        "Protoplast_movement_overlay2": {
            "OutPlatetype":"pcrplate_skirted_riser",
			"OutPlatetype2":"pcrplate_with_incubater",
			"AgarPlate":"falcon6wellAgar",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"Plateoutvolume":"50ul",
			"TransformedCellsVol":"190ul",
			"OutWell":"A1",
			"OutWell2":"A1"
        },
        "Protoplast_movement_overlay3": {
            "OutPlatetype":"pcrplate_skirted_riser",
			"OutPlatetype2":"pcrplate_with_incubater",
			"AgarPlate":"falcon6wellAgar",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"Plateoutvolume":"50ul",
			"TransformedCellsVol":"190ul",
			"OutWell":"A1",
			"OutWell2":"A1"
        },
        "Protoplast_movement_overlay4": {
            "OutPlatetype":"pcrplate_skirted_riser",
			"OutPlatetype2":"pcrplate_with_incubater",
			"AgarPlate":"falcon6wellAgar",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"Plateoutvolume":"50ul",
			"TransformedCellsVol":"190ul",
			"OutWell":"A1",
			"OutWell2":"A1"
        },
        "Protoplast_movement_overlay5": {
            "OutPlatetype":"pcrplate_skirted_riser",
			"OutPlatetype2":"pcrplate_with_incubater",
			"AgarPlate":"falcon6wellAgar",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"Plateoutvolume":"50ul",
			"TransformedCellsVol":"190ul",
			"OutWell":"A1",
			"OutWell2":"A1"
        },
        "Protoplast_movement_overlay6": {
            "OutPlatetype":"pcrplate_skirted_riser",
			"OutPlatetype2":"pcrplate_with_incubater",
			"AgarPlate":"falcon6wellAgar",
            "Cells":"protoplasts",
			"DNA":"dna_part",
			"PEG":"PEG",
			"Partname":"thepart",
			"CellVol":"10ul",
			"DNAVol":"2ul",
			"PEGVol":"190ul",
			"Plateoutvolume":"50ul",
			"TransformedCellsVol":"190ul",
			"OutWell":"A1",
			"OutWell2":"A1"
        }
    }
}