{
    "Parameters": {
        "MakeMedia":{
            "Name": "Custom_mediaRecipe",
            "Water": "water",
            "TotalVolume": "100ul",
            "LiqComponentVolumes": [
			"10ul",
			"10ul"
			],
			"SolidComponentMasses":[
			"0.1mg",
			"0.2mg"
			],
			"SolidComponentDensities":[
			"1000kg/m^3",
			"1000kg/m^3"
			],
            "LiqComponents":[
			"10x_M9Salts",
			"100x_MEMVitamins"
			],
			"SolidComponents":[
			"Yeast extract",
			"Tryptone"
			],
			"PH_setPoint": 7.2,
			"PH_tolerance":0.2,
			"PH_setPointTemp": "25C",
            "Vessel": "1L_DuranBottle"
        }
    }
}
