{
    "Parameters": [{
        "MakeMedia":{
            "Name": "Custom_mediaRecipe",
            "Water": "component:water",
            "TotalVolume": "100ul",
            "LiqComponentVolumes": [
			"10ul",
			"10ul"
			],
			"SolidComponentMasses":[
			"0.1mg",
			"0.2mg"
			],
			"SolidComponentDensities":[
			"1000kg/m^3",
			"1000kg/m^3"
			],
            "LiqComponents":[
			"component:10x_M9Salts",
			"component:100x_MEMVitamins"
			],
			"SolidComponents":[
			"component:Yeast extract",
			"component:Tryptone"
			],
			"PH_setPoint": 7.2,
			"PH_tolerance":0.2,
			"PH_setPointTemp": "25C",
            "Vessel": "plate:1L_DuranBottle",
            "TipType": "tipbox:Gilson20"
        }
    }],
    "Config": {
        "OUTPUT_COUNT": 1
    }
}
