{
    "Parameters": {
        "MakeMedia": {
            "LiqComponentVolumes": [
                "10ul",
                "10ul"
            ],
            "LiqComponents": [
                "10x_M9Salts",
                "100x_MEMVitamins"
            ],
            "Name": "Custom_mediaRecipe",
            "PH_setPoint": 7.2,
            "PH_setPointTemp": "25C",
            "PH_tolerance": 0.2,
            "SolidComponentDensities": [
                "1000kg/m^3",
                "1000kg/m^3"
            ],
            "SolidComponentMasses": [
                "0.1mg",
                "0.2mg"
            ],
            "SolidComponents": [
                "Yeast extract",
                "Tryptone"
            ],
            "TotalVolume": "100ul",
            "Vessel": "1L_DuranBottle",
            "Water": "water"
        }
    }
}
