{
    "Parameters": {
        "AccuracyTest": {
            "DXORJMP": "JMP",
            "Diluent": "water",
            "Imagefilename": "star.png",
            "LHPolicy": "PostMix",
            "NumberofBlanks": 5,
            "NumberofReplicates": 12,
            "OutPlate": "greiner384_riser",
            "OutputFilename": "AccuracytestPostMixHVoutput_test.xlsx",
            "Printasimage": true,
            "TestSolVolumes": [
               "0.5ul",
			    "1ul",
				"2ul",
				"5ul",
				"7.5ul",
				"10ul",
				"25ul",
                "30ul",
                "35ul",
                "40ul",
                "45ul",
                "50ul"
            ],
            "TestSols": [
                "tartrazine"
            ],
            "TotalVolume": "100ul",
            "UseLiquidPolicyForTestSolutions": true
        }
    }
}
