{
    "Parameters": {
        "MoClo_design":{
            "Constructname": "Moflo2Assemblyproduct", 				
            "Partsinorder": [
            "BBa_I14018",
            "Rbs",
            "BBa_E0020", 
            "Term"
            ],
            "PartMoClotypesinorder": [
            "Pro",
            "5U + NT1",
            "CDS1",
            "3U + Ter"
            ],
			"Vector":"pAGM1311_M",
            "AssemblyStandard": "MoClo",
            "Level": "Level0"
        }
    }
}
