{
    "Parameters": [{
        "MoClo_design":{
            "Constructname": "Moflo2Assemblyproduct", 				
            "Partsinorder": [
            "BBa_I14018",
            "Rbs",
            "BBa_", 
            "Term"
            ],
            "PartMoClotypesinorder": [
            "Pro",
            "5U + NT1",
            "CDS1",
            "3U + Ter"
            ],
			"RestrictionsitetoAvoid":[
			"EcoRI",
			"PvuII"
			],
			"Vector":"pAGM1311_M",
            "AssemblyStandard": "MoClo",
            "Level": "Level0"
        }
    }],
    "Config": {
        "OUTPUT_COUNT": 1
    }
}
