{
    "Parameters": {
        "Design1": {
            "Parts": [ 
				"BBa_K557010",
				"BBa_K557010",
				"BBa_K557010",
				"BBa_K557010" 
			],
			"Vector": "EU593758",
			"RE": "SapI"
		},
		"Mix1": {
			"ComponentsV": [
				"1ul",
				"1ul",
				"1ul",
				"1ul"],
			"VectorV": "1ul",
			"BufferV": "1ul",
			"LigaseV": "1ul",
			"REV": "1ul",
			"ATPV": "1ul",
			"ReactionVolume": "20ul",
			"Vector": "standard_cloning_vector_mark_1",
			"Buffer": "CutsmartBuffer",
			"Ligase": "T4Ligase",
			"ATP": "ATP",
			"RE": "SapI",
			"Water": "water",
			"InPlate": "greiner384_riser",
			"OutPlate": "pcrplate_with_cooler",
			"ReactionTemp": "25C",
			"ReactionTime": "60000"
			
		}
    }
}