{
    "Parameters": {
        "Evaporationrate": {
            "Airvelocity": "0m/s",
            "Executiontime": "7200s",
            "Liquid": "water",
            "Pa": "101325Pa",
            "Platetype": "96DSW_axygen",
            "Relativehumidity": 0.28,
            "Temp": "25C",
            "Volumeperwell": "5000nl"
        }
    }
}
