{
    "Parameters": {
        "Evaporationrate": {
            "Airvelocity": "0m/s",
            "Executiontime": "7200s",
            "Liquid": "water",
            "Pa": "99700Pa",
            "Plate": "greiner384",
            "Relativehumidity": 0.35,
            "Temp": "23.2C",
            "Volumeperwell": "1000ul"
        }
    }
}
