{
    "Parameters": {
        "Evaporationrate": {
            "Airvelocity": "0m/s",
            "Executiontime": "3960s",
            "Liquid": "water",
            "Pa": "100800Pa",
            "Platetype": "SRWFB96",
            "Relativehumidity": 0.33,
            "Temp": "23.0C",
            "Volumeperwell": "100ul"
        }
    }
}
