{
  "Parameters": [{
    "Evaporationrate": {
      "Airvelocity":0m/s,
      "Liquid": "water",
      "Platetype": "96DSW_axygen",
      "Pa": 101325Pa,
      "Temp": 25ËšC,
      "Relativehumidity": 0.28,
      "ExecutionTime": 7200s,
	  "Volumeperwell" : 5000nl
    }
  }],
    "Config": {
        "OUTPUT_COUNT": 1
    }
}
