{
  "Parameters": {
    "Evaporationrate": {
      "Airvelocity": "0m/s",
      "Liquid": "water",
      "Platetype": "96DSW_axygen",
      "Pa": "101325Pa",
      "Temp": "25C",
      "Relativehumidity": 0.28,
      "Executiontime": "7200s",
      "Volumeperwell" : "5000nl"
    }
  }
}
