{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"rainbow1.png",
      "Cyan": "Cyan",
	"Magenta": "Magenta",
	"Yellow": "Yellow_ink",
	"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "20ul"
    }
  }
}


