{
  "Parameters": [{
    "PipetteImage": {
		"Imagefilename":"rainbow1.png",
      "Cyan": "component:Cyan",
	"Magenta": "component:Magenta",
	"Yellow": "component:Yellow_ink",
	"Black": "component:Black",
      "Outplate": "plate:greiner384_riser",
      "TipType": "tipbox:Gilson20",
      "VolumeForFullcolour": "20ul"
    }
  }],
  "Config": {
    "OUTPUT_COUNT": 128
  }
}


