{
    "Parameters": {
        "MakeBuffer": {
            "Buffername": "Cutsmart1X",
            "Bufferstock": "CutsmartBuffer",
            "Bufferstockconc": "5M/l",
            "Bufferstockvolume": "0.2ml",
            "Diluent": "water",
            "Diluentvolume": "0.3ml",
            "FinalConcentration": "2mg/l",
            "FinalVolume": "0.5ml",
            "InPlate": "pcrplate_with_cooler",
            "OutPlate": "pcrplate_with_cooler"
        }
    }
}
