{
    "Parameters": {
        "MakeBuffer": {
            "Buffername": "tartrazine_300uM",
            "Bufferstock": "tartrazine",
            "Bufferstockconc": "0.006M/l",
            "Bufferstockvolume": "45ml",
            "Diluent": "water",
            "Diluentvolume": "0.3ml",
            "FinalConcentration": "0.0003M/l",
            "FinalVolume": "50ml",
           "InPlate": "pcrplate_with_cooler",
            "OutPlate": "pcrplate_with_cooler"
        }
    }
}
