{
    "Parameters": {
        "ScreenLHPolicies_Awesome": {
            "Diluent": "water",
            "TestSols": [
			"tartrazine"
			],
            "NumberofReplicates": 1,
            "OutPlate": "greiner384_riser",
            "TestSolVolumes": [
			
			"8ul"
			],
			"LHDOEFile":"FullFactorial.xlsx",
			"DXORJMP":"JMP",
			"Printasimage": false,
			"Imagefilename": "star1.png",
            "TotalVolume": "20ul",
			"NumberofBlanks": 5
        }
    }
}

