{
    "Parameters": {
        "ScreenLHPolicies_Awesome": {
            "Diluent": "water",
            "TestSols": [
			"tartrazine"
			],
            "NumberofReplicates": 3,
            "OutPlate": "greiner384_riser",
            "TestSolVolumes": [
			"0.5ul",
			"1ul",
			"2ul"
			],
			"LHDOEFile":"FullFactorial.xlsx",
			"DXORJMP":"JMP",
			"OutputFilename":"jmpfactorialDoeoutput.xlsx",
			"Printasimage": false,
			"Imagefilename": "star1.png",
            "TotalVolume": "20ul",
			"NumberofBlanks": 5
        }
    }
}

