{
    "Parameters": {
        "ScreenLHPolicies_Awesome": {
            "Diluent": "water",
            "TestSols": [
			"tartrazine"
			],
            "NumberofReplicates": 2,
            "OutPlate": "greiner384_riser",
            "TestSolVolumes": [
			"1ul",
			"2ul",
			"3ul"
			],
			"LHDOEFile":"8run4cpFactorial.xlsx",
			"DXORJMP":"JMP",
			"OutputFilename":"jmpfactorialDoeoutput_test.xlsx",
			"Printasimage": true,
			"Imagefilename": "star1.png",
            "TotalVolume": "20ul",
			"NumberofBlanks": 0
        }
    }
}

