{

    "Parameters": {
        "MultiChannelTest": {
				"Vols": ["1ul","1ul","1ul","1ul","1ul","1ul","1ul","1ul"],
				"Parts":["water","water","water","water","water","water","water","water"],
				"OutputPlateType":"pcrplate_skirted_riser"
        }
    }
}
