{
    "Parameters": {
        "PlateOut": {
            "AgarPlate": "falcon6wellAgar",
            "Diluent": "water",
            "DilutionX": 1,
            "IncubationTemp": "25C",
            "IncubationTime": "57600s",
            "Plateoutvolume": "1000ul",
            "RecoveredCells": "neb5compcells"
        }
    }
}
