{
    "Parameters": {
        "PlateOut":{
            "RecoveredCells": "neb5compcells",
			"Diluent": "water",
			"DilutionX": 1,
			"IncubationTime": "57600s",
			"IncubationTemp": "25C",
			"Plateoutvolume": "100ul",
			"AgarPlate": "falcon6wellAgar"
        }
    }
}
