{
    "Parameters": {
        "RemoveRestrictionSites":{
            "Sequencekey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGAGCTCGGGGGGGGGGGGGGGGGGGGGGGGG", 				
            "RestrictionsitetoAvoid": [
            "SacI"
            ],
            "RemoveifnotinORF": true,
			"PreserveTranslatedseq":true,
			"EnzymeforRestrictionmapping":"BsaI"
        }
    }
}
