{
    "Parameters": {
        "Thawtime": {
            "Airvelocity": "20m/s",
            "BulkTemp": "0\u02daC",
            "Fillvolume": "200ul",
            "Fudgefactor": 2,
            "Liquid": "water",
            "Platetype": "PCR_plate",
            "SurfaceTemp": "25\u02daC"
        }
    }
}
