{
  "Parameters": [{
    "Thawtime": {
      "Platetype": "PCR_plate",
      "Liquid": "water",
      "Airvelocity": 20m/s,
      "SurfaceTemp": "25˚C",
      "BulkTemp": "0˚C",
      "Fillvolume": "200ul",
      "Fudgefactor": 2
    }
  }],
    "Config": {
        "OUTPUT_COUNT": 1
    }
}
