{
    "Parameters": {
        "Thawtime": {
            "Airvelocity": "20m/s",
            "BulkTemp": "0C",
            "Fillvolume": "200ul",
            "Fudgefactor": 2,
            "Liquid": "water",
            "Platetype": "pcrplate_skirted",
            "SurfaceTemp": "25C"
        }
    }
}
