{
  "Parameters": {
    "EnterNameForYourParameters1": {
      "InputVariable": "Some component in factory",
      "OutPlate": "greiner384",
      "ParameterVariablestring": "Hello World!",
      "ParameterVariableAsValuewithunit": "10ul",
      "ParameterVariableAsint": 1
    },
    "EnterNameForYourParameters2": {
      "InputVariable": "component:Some component in factory",
      "OutPlate": "greiner384",
      "ParameterVariablestring": "Hello again",
      "ParameterVariableAsValuewithunit": "100ul",
      "ParameterVariableAsint": 2
    }
  }
}
