{
    "Parameters": {
        "FindPartsthat":{ 				
           "Parttypes": [
              "Terminator"
            ],
	    "Partdescriptions": [
              "Double"
            ],
            "OnlyreturnAvailableParts": true,
            "OnlyreturnWorkingparts": true
        }
    }
}

