{
    "Parameters": {
        "FindPartsthat": {
            "OnlyreturnAvailableParts": true,
            "OnlyreturnWorkingparts": true,
            "Partdescriptions": [
                "strong"
            ],
            "Parttypes": [
                "RBS"
            ]
        }
    }
}
