{
    "Parameters": {
        "FindPartsthat": {
            "OnlyreturnAvailableParts": true,
            "OnlyreturnWorkingparts": true,
            "Partdescriptions": [
                "Double"
            ],
            "Parttypes": [
                "Terminator"
            ]
        }
    }
}
