{
    "Parameters": [{
        "FindPartsthat":{ 				
           "Parttypes": [
            "Terminator",
            
            ],
		 "Partdescriptions": [
            "Double",
            ],
        }
    }],
    "Config": {
        "OUTPUT_COUNT": 1
    }
}

