{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"kirby_8_bits_by_sumomogirl2.jpg",
      "Cyan": "Cyan",
	"Magenta": "Magenta",
	"Yellow": "Yellow_ink",
	"Black": "Black",
      "OutPlate": "DSW96_riser",
      "VolumeForFullcolour": "150ul"
    }
  }
}


