{
    "Parameters": {
        "ScreenLHPolicies": {
			"DXORJMP":"JMP",
			"LHDOEFile":"8run4cpFactorial.xlsx",
            "Diluent": "water",
            "TestSols": [
			"tartrazine"
			],
            "NumberofReplicates": 1,
            "OutPlate": "greiner384_riser",
            "TestSolVolume": "30ul",
            "TotalVolume": "100ul"
        }
    }
}

