{
    "Parameters": {
        "newparams": {
            "LiquidVolume": "10ul",
            "Liquidname": "Evian",
            "OutPlate": "greiner384_riser",
            "Startingsolution": "water"
        }
    }
}
