{
  "Parameters": [ {
	"DNAgelParams": {
    "Water":"component:water",
	"Sampletotest": "component:1kb DNA Ladder",
	"Mixingpolicy":"gelloading",
	"Loadingdye":"component:Blue",
    "DNAgel": "plate:EPAGE48",
    "TipType": "tipbox:Gilson20",
    "WaterVol":"10ul",
    "Loadingdyevolume": "0ul",
	"DNAgelrunvolume":"15ul",
	"Samplenumber":2,
	"Samplenames":[
	"Marker 1",
	"Marker2"
	],
	"Loadingdyeinsample":true
  }
},
{
	"DNAgelParams": {
    "Water":"component:water",
	"Sampletotest": "component:DNAsolution",
	"Mixingpolicy":"gelloading",
	"Loadingdye":"component:Blue",
    "DNAgel": "plate:EPAGE48",
    "TipType": "tipbox:Gilson20",
    "WaterVol":"10ul",
    "Loadingdyevolume": "0ul",
	"DNAgelrunvolume":"15ul",
	"Samplenumber":12,
	"Samplenames":[
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"10",
	"11",
	"12"
	],
	"Loadingdyeinsample":true
  }
}],
  "Config": {
    "OUTPUT_COUNT": 14
  }
}