{
  "Parameters": [ {
	"DNAgelParams": {
    "Water":"component:water",
	"Sampletotest": "component:1kb DNA Ladder",
	"Mixingpolicy":"load",
	"Loadingdye":"component:Blue",
    "InPlate":"plate:greiner384",
	"DNAgel": "plate:EPAGE48",
    "TipType": "tipbox:Gilson20",
    "WaterVol":"10ul",
    "Loadingdyevolume": "0ul",
	"DNAgelrunvolume":"15ul",
	"Samplenumber":2,
	"Samplenames":[
	"Marker 1",
	"Marker2",
	],
	"Loadingdyeinsample":true
  }
},
{
	"DNAgelParams": {
    "Water":"component:water",
	"Sampletotest": "component:DNAsolution",
	"Mixingpolicy":"load",
	"Loadingdye":"component:Blue",
	"InPlate":"plate:greiner384",
    "DNAgel": "plate:EPAGE48",
    "TipType": "tipbox:Gilson20",
    "WaterVol":"10ul",
    "Loadingdyevolume": "0ul",
	"DNAgelrunvolume":"15ul",
	"Samplenumber":2,
	"Samplenames":[
	"load1",
	"load2",
	],
	"Loadingdyeinsample":true
  }
},
{
	"DNAgelParams": {
    "Water":"component:water",
	"Sampletotest": "component:DNAsolution",
	"Mixingpolicy":"loadlow",
	"Loadingdye":"component:Blue",
	"InPlate":"plate:greiner384",
    "DNAgel": "plate:EPAGE48",
    "TipType": "tipbox:Gilson20",
    "WaterVol":"10ul",
    "Loadingdyevolume": "0ul",
	"DNAgelrunvolume":"15ul",
	"Samplenumber":2,
	"Samplenames":[
	"loadlow1",
	"loadlow2"
	],
	"Loadingdyeinsample":true
  }
}],
  "Config": {
    "OUTPUT_COUNT": 6
  }
}