{
  "Parameters": [{
    "DNAgelParams": {
    "Sampletotest": "component:water",
	"Loadingdye":"component:water",
    "DNAgel": "plate:greiner384",
    "TipType": "tipbox:Gilson20",
    "Loadingdyevolume": "0ul",
	"DNAgelrunvolume":"20ul",
	"Loadingdyeinsample":true
  },
}],
  "Config": {
    "OUTPUT_COUNT": 1
  }
}