{
  "Parameters": [{
    "Assaysetup": {
      "Buffer": "component:water",
	"Substrate": "component:CutsmartBuffer",
	"Enzyme": "component:T4Ligase",
      "Outplate": "plate:pcrplate_with_cooler",
      "TipType": "tipbox:Gilson20",
      "TotalVolume": "100ul",
      "SubstrateVolume": "10ul",
	"EnzymeVolume": "10ul",
	"NumberofReactions":3
    }
  }],
  "Config": {
    "OUTPUT_COUNT": 3
  }
}