{
  "Parameters": {
    "Assaysetup": {
      "Buffer": "water",
      "Substrate": "CutsmartBuffer",
      "Enzyme": "T4Ligase",
      "OutPlate": "reservoir",
      "TipType": "Gilson200",
      "TotalVolume": "100ul",
      "SubstrateVolume": "30ul",
      "EnzymeVolume": "30ul",
      "NumberofReactions": 1
    }
  }
}
