{
    "Parameters": {
        "Assaysetup": {
            "Buffer": "water",
            "Enzyme": "T4Ligase",
            "EnzymeVolume": "30ul",
            "NumberofReactions": 1,
            "OutPlate": "reservoir",
            "Substrate": "CutsmartBuffer",
            "SubstrateVolume": "30ul",
            "TipType": "Gilson200",
            "TotalVolume": "100ul"
        }
    }
}
