{
    "Parameters": {
        "Transformation":{
            "Reaction": "dna_part",
            "ReadyCompCells": "neb5compcells",
            "CompetentCellvolumeperassembly": "50ul",
            "Reactionvolume": "10ul",
			"Postplasmidtime": "300s",
			"Postplasmidtemp": "2C",
            "OutPlate": "pcrplate_with_cooler"
        }
    }
}
