{
    "Parameters": {
        "PipetteImage": {
            "AvailableColours": [
                "red",
                "white",
                "blue",
                "green",
                "yellow",
                "black"
            ],
            "Colourcomponents": [
                "red",
                "white",
                "blue",
                "green",
                "yellow",
                "black"
            ],
            "Imagefilename": "mario.png",
            "OnlythisColour": "",
            "OutPlate": "greiner384_riser",
            "Palettename": "Palette1",
            "VolumePerWell": "10ul"
        }
    }
}
