{
  "Parameters": [{
    "PipetteImage": {
      "Colourcomponents": [
	"component:red",
	"component:white",
	"component:blue",
	"component:green",
	"component:yellow",
	"component:black"
	],
	"OnlythisColour":"",
	  "Imagefilename": "mario.png",
		"Palettename":"Palette1",
		"AvailableColours":[
		"green",
		],
      "Outplate": "plate:greiner384_riser",
      "TipType": "tipbox:Gilson20",
      "VolumePerWell": "10ul"
    }
  }],
  "Config": {
    "OUTPUT_COUNT": 143
  }
}



