{
  "Parameters": {
    "PipetteImage": {
      "Imagefilename": "apple.jpg",
	  "UVimage": false,
	  "Rotate":false,
	  "AutoRotate":true,
	  "UseLiquidClass":"water",
		"Palettename":"Neon",
	      "Subsetnames": [
		"black",
		"white",
		"purple",
		"blue",
		"green",
		"yellow",
		"orange",
		"red",
		"pink"
		],
		"OnlythisColour":"",
		"Notthiscolour":"white",
      "OutPlate": "greiner384_riser",
      "VolumePerWell": "100ul"
    }
  }
}


