{
  "Parameters": {
    "PipetteImage": {
      "Colourcomponents": [
	"red",
	"white",
	"blue",
	"green",
	"yellow",
	"black"
	],
	"OnlythisColour":"",
	"NotthisColour":"white",
	  "Imagefilename": "pacman.png",
		"Palettename":"Palette1",
		"AvailableColours":[
		"red",
		"white",
		"blue",
		"green",
		"yellow",
		"black"
		],
      "OutPlate": "greiner384_riser",
      "VolumePerWell": "100ul"
    }
  }
}


