{
  "Parameters": {
    "PipetteImage": {
      "Colourcomponents": [
	"black",
	"white",
	"purple",
	"blue",
	"green",
	"yellow",
	"orange",
	"red",
	"pink"
	],
	"OnlythisColour":"",
	"NotthisColour":"white",
	  "Imagefilename": "jenkins.jpeg",
		"Palettename":"Neon",
      "OutPlate": "greiner384_riser",
      "VolumePerWell": "100ul"
    }
  }
}


