{
  "Parameters": {
    "PipetteImage": {
      "Imagefilename": "turing.jpg",
	  "UVimage": false,
	  "Rotate":false,
	  "AutoRotate":true,
	  "CheckResizeAlgorithms":true,
	  "UseLiquidClass":"water",
		"Palettename":"Palette1",
		"Subset":true,
	      "Subsetnames": [
		"black",
		"white"
		],
		"OnlythisColour":"",
		"Notthiscolour":"",
      "OutPlate": "Agarplateforpicking384_riser",
      "VolumePerWell": "2ul"
    }
  }
}


