{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"hitler_cat.jpg",
		"Diluent":"water",
	"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "150ul"
    }
  }
}


