{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"carmen.jpeg",
		"Rotate": false,
		"Diluent":"water",
		"MinimumBlackpercentagethreshold":0.21,
		"OnlyHighVolumetips": true,
		"Negative": false,
	"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "100ul"
    }
  }
}


