{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"vader.jpeg",
		"Rotate": false,
		"AutoRotate": true,
		"Diluent":"water",
		"MinimumBlackpercentagethreshold":0.1,
		"OnlyHighVolumetips": true,
		"DontMix":false,
		"Negative": false,
		"PosterizeImage": false,
		"PosterizeLevels": 4,
		"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "100ul"
    }
  }
}



