{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"ziggy3_384.jpg",
		"Rotate": false,
		"AutoRotate": true,
		"Diluent":"water",
		"MinimumBlackpercentagethreshold":0.2,
		"OnlyHighVolumetips": true,
		"Negative": true,
		"PosterizeImage": true,
		"PosterizeLevels": 4,
		"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "100ul"
    }
  }
}



