{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"darwin.png",
		"Rotate": false,
		"AutoRotate": true,
		"Diluent":"water",
		"MinimumBlackpercentagethreshold":0.1,
		"MaxBlackPercentagethreshold": 0.9,
		"OnlyHighVolumetips": true,
		"DontMix":false,
		"Negative": true,
		"PosterizeImage": true,
		"PosterizeLevels": 8,
		"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "100ul"
    }
  }
}



