{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"ziggy3_384.jpg",
		"Rotate": false,
		"Diluent":"water",
		"MinimumBlackpercentagethreshold":0.0,
		"OnlyHighVolumetips": false,
		"Negative": false,
		"PosterizeImage": false,
		"PosterizeLevels": 2,
	"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "100ul"
    }
  }
}


