{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"imgres.jpg",
		"Rotate": true,
		"Diluent":"water",
		"MinimumBlackpercentagethreshold":0.20,
		"OnlyHighVolumetips": true,
		"Negative": true,
	"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "100ul"
    }
  }
}


