{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"IMG_4153.JPG",
		"Rotate": false,
		"AutoRotate": true,
		"Diluent":"water",
		"MinimumBlackpercentagethreshold":0.3,
		"MaxBlackPercentagethreshold": 0.7,
		"OnlyHighVolumetips": true,
		"MixingLiquidClass": "NeedToMix",
		"DontMix":false,
		"Negative": false,
		"PosterizeImage": true,
		"PosterizeLevels": 8,
		"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "120ul"
    }
  }
}



