{
  "Parameters": {
    "PipetteImage": {
		"Imagefilename":"8-Bit-Pixel-Handlebar-Moustache.png",
		"Rotate": false,
		"AutoRotate": true,
		"Diluent":"water",
		"MinimumBlackpercentagethreshold":0.3,
		"MaxBlackPercentagethreshold": 0.7,
		"OnlyHighVolumetips": false,
		"SkipWhite": true,
		"MixingLiquidClass": "NeedToMix",
		"NonMixingClass": "water",
		"DontMix":true,
		"Negative": false,
		"PosterizeImage": true,
		"PosterizeLevels": 2,
		"Black": "Black",
      "OutPlate": "greiner384_riser",
      "VolumeForFullcolour": "25ul"
    }
  }
}



